spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  application: microservicecloud-config-atguigu-dev

---
spring:
  profiles: test
  application: microservicecloud-config-atguigu-test
    